### ISSUE TITLE
특정 모드를 구독하고 알파 추출기의 추출 모드 선택을 눌렀을 때 오류가 발생합니다.

### ISSUE THREAD

**Issue by BluePineForest** [Han-ju/AlphaExtractor#3]
스팀의 Stop, Drop, And Roll! [BAL] 라는 모드를 구독하고 알파 추출기의 추출 모드 선택을 눌렀을 때 해당 오류가 발생하여, 어떠한 모드도 선택이 되지 않아 추출이 불가능해집니다.
해당 모드 주소 [https://steamcommunity.com/sharedfiles/filedetails/?id=2362707956](url)

오류 발생시의 스샷입니다.
![알파 추출기 오류](https://user-images.githubusercontent.com/77609045/104896931-1f129500-59bb-11eb-839e-f6267290b709.PNG)

해당 오류 발생시 error_report.txt에 기록된 내용입니다.

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1884, in __call__
  File "AlphaExtractor.py", line 1146, in <lambda>
  File "AlphaExtractor.py", line 1135, in onClick
  File "AlphaExtractor.py", line 418, in loadSelectMod
  File "xml\etree\ElementTree.py", line 1229, in parse
  File "xml\etree\ElementTree.py", line 580, in parse
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 18, column 522

**Comment by Han-ju** [comment]
해당 사항 확인 결과 모드 제작자가 About.xml에서 XML 문법 오류를 발생시켜 프로그램이 XML을 분석할 수 없었던 문제였습니다.
제작자가 XML 문법 오류를 해결할 수 있도록 해당 모드 제작자에게 관련 사항을 전달하였고, 동시에 문법 오류를 발생시킨 xml 파일은 없는 것으로 취급하도록 수정할 예정입니다.

**Comment by BluePineForest** [comment]
네, 고생하셨습니다.
